name: 'CI'

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    name: 'Ruby ${{ matrix.ruby-version }}, Rails ${{ matrix.rails-version }}'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        ruby-version:
          - '2.5.9'
          - '2.6.9'
          - '2.7.5'
        rails-version:
          - '6.1.0'
    env:
      RAILS_VERSION: '${{ matrix.rails-version }}'
    steps:
    - uses: 'actions/checkout@v2'
    - uses: 'ruby/setup-ruby@v1'
      with:
        ruby-version: '${{ matrix.ruby-version }}'
        bundler-cache: true
    - name: 'Run tests'
      run: 'bundle exec rake'
